apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: elasticsearch
  namespace: graylog
spec:
  replicas: 4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: elasticsearch
    spec:
      containers:
      - args:
        - elasticsearch
        - -Ecluster.name=graylog
        image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
        name: elasticsearch
        resources: {}
      restartPolicy: Always
status: {}
