apiVersion: v1
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-persistent-storage
  namespace: graylog
spec:
  storageClassName: default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi