apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: graylog
  labels:
    name: mongo
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 27017
    targetPort: 27017
  selector:
    role: mongo